### ISSUE TITLE
amocrm.v2.exceptions.AmoApiException: Connection aborted.

### ISSUE THREAD

**Issue by Vladik288** [Krukov/amocrm_api#107]
Добрый день, возникает такая ошибка Traceback (most recent call last):
  File "/home/app/bot/handlers/echo.py", line 91, in mailing_func
    for i in leads:
  File "/usr/local/lib/python3.10/site-packages/amocrm/v2/manager.py", line 27, in filter
    for data in self._interaction.get_all(*args, include=self._model._get_embedded_fields(), **kwargs):
  File "/usr/local/lib/python3.10/site-packages/amocrm/v2/interaction.py", line 112, in get_all
    for data in self._all(self._get_path(), include=include, query=query, filters=filters, order=order):
  File "/usr/local/lib/python3.10/site-packages/amocrm/v2/interaction.py", line 77, in _all
    response, _ = self._list(
  File "/usr/local/lib/python3.10/site-packages/amocrm/v2/interaction.py", line 72, in _list
    return self.request("get", path, params=params, include=include)
  File "/usr/local/lib/python3.10/site-packages/amocrm/v2/interaction.py", line 57, in request
    return self._request(method, path, data=data, params=params, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/amocrm/v2/interaction.py", line 40, in _request
    raise exceptions.AmoApiException(e.args[0].args[0])  # Sometimes Connection aborted.
amocrm.v2.exceptions.AmoApiException: Connection aborted.
Перезапуская сервер и все работает, а также токен не хранится больше 2 дней, почему? приходится обновлять, запросы каждый день на сервер идут, в чем может быть причина?

**Comment by Krukov** [comment]
приложение в докере работает ? 

второе без кода тяжело понять что не так - ну судя по ошибке вы что то не то в responsible_user_id указываете

**Comment by Vladik288** [comment]
Да в докере, там просто сохраяю сделку по-другому статусу, 3 дня работало и перестало.
Удобно будет в tg bbizon?

**Comment by Vladik288** [comment]
![image](https://github.com/Krukov/amocrm_api/assets/55274156/2e36605b-e56e-48d3-81c4-ea6bc5a48cf6)

**Comment by Vladik288** [comment]
Пока что 1 вопрос волнует, со 2 разобрался вроде, почему он обрвывает кконект
