### ISSUE TITLE
Не работает lead.notes.objects.create(text="Примечание") и lead.notes(text="Примечание").save()

### ISSUE THREAD

**Issue by Evgenij-evso** [Krukov/amocrm_api#119]
@Krukov 
Не работает не lead.notes.objects.create(text="Примечание") не lead.notes(text="Примечание").save()

> lead = Lead()
> lead.name = "ТЕСТОВЫЙ ЗАПРОС"
> lead.notes(text = 'Примечание').save()

так выдает - ошибку

> Traceback (most recent call last):
>   File "c:\Progect\cooleso.ru_bot\testamo.py", line 35, in <module>
>     lead.notes(text = 'Сообщение').save()
>   File "C:\Users\Евгений\AppData\Local\Programs\Python\Python39\lib\site-packages\amocrm\v2\model.py", line 51, in save  
>     self.create()
>   File "C:\Users\Евгений\AppData\Local\Programs\Python\Python39\lib\site-packages\amocrm\v2\model.py", line 59, in create
>     self._data["id"] = self._manager.create(self._data).id
>   File "C:\Users\Евгений\AppData\Local\Programs\Python\Python39\lib\site-packages\amocrm\v2\manager.py", line 16, in create
>     return self._model(data=self._interaction.create(data=data or kwargs))
>   File "C:\Users\Евгений\AppData\Local\Programs\Python\Python39\lib\site-packages\amocrm\v2\interaction.py", line 123, in create
>     response, status = self.request("post", self._get_path(), data=[data])
>   File "C:\Users\Евгений\AppData\Local\Programs\Python\Python39\lib\site-packages\amocrm\v2\interaction.py", line 57, in request
>     return self._request(method, path, data=data, params=params, headers=headers)
>   File "C:\Users\Евгений\AppData\Local\Programs\Python\Python39\lib\site-packages\amocrm\v2\interaction.py", line 51, in _request
>     raise exceptions.AmoApiException("Wrong status {} ({})".format(response.status_code, response.text))
> amocrm.v2.exceptions.AmoApiException: Wrong status 404 ({"title":"Not Found","type":"https://httpstatus.es/404","status":404,"detail":"Cannot POST https://autoschoolkoleso.amocrm.ru/leads/None/notes!"})

а если так

> lead = Lead()
> lead.name = "ТЕСТОВЫЙ ЗАПРОС"
> lead.notes(text = 'Примечание')
> lead.save()

то примечание просто не появляется

Ваще не понимаю почему так происходит((

**Comment by andron23** [comment]
Возможно вам поможет - мы вот так создаем примечание: 


```python
# Здесь our_lead - объект какой-то сделки
our_lead.notes.objects.create(
    note_type="common",
    text="Текст примечания",
)
```
