### ISSUE TITLE
IndexError: list index out of range при парсинге данных Event

### ISSUE THREAD

**Issue by AndrejGorodnij** [Krukov/amocrm_api#77]
Возникает на разных свойствах, ['note'], ['link'] и т.д при переборе и выводе каждого элемента списка событий в консоль.

> Traceback (most recent call last):
  File "/home/rusty/Client-projects/AmoCrmDB/another_wrap.py", line 137, in <module>
    print(i)
  File "/home/rusty/Client-projects/AmoCrmDB/venv/lib/python3.10/site-packages/amocrm/v2/model.py", line 40, in __repr__
    fields = [
  File "/home/rusty/Client-projects/AmoCrmDB/venv/lib/python3.10/site-packages/amocrm/v2/model.py", line 41, in <listcomp>
    "{} = {}".format(field.name, getattr(self, attr))
  File "/home/rusty/Client-projects/AmoCrmDB/venv/lib/python3.10/site-packages/amocrm/v2/fields.py", line 33, in __get__
    return self.on_get_instance(instance, data)
  File "/home/rusty/Client-projects/AmoCrmDB/venv/lib/python3.10/site-packages/amocrm/v2/entity/events.py", line 93, in on_get_instance
    return value[0]["note"]["id"]
IndexError: list index out of range

> Traceback (most recent call last):
  File "/home/rusty/Client-projects/AmoCrmDB/another_wrap.py", line 133, in <module>
    print(i)
  File "/home/rusty/Client-projects/AmoCrmDB/venv/lib/python3.10/site-packages/amocrm/v2/model.py", line 40, in __repr__
    fields = [
  File "/home/rusty/Client-projects/AmoCrmDB/venv/lib/python3.10/site-packages/amocrm/v2/model.py", line 41, in <listcomp>
    "{} = {}".format(field.name, getattr(self, attr))
  File "/home/rusty/Client-projects/AmoCrmDB/venv/lib/python3.10/site-packages/amocrm/v2/fields.py", line 33, in __get__
    return self.on_get_instance(instance, data)
  File "/home/rusty/Client-projects/AmoCrmDB/venv/lib/python3.10/site-packages/amocrm/v2/entity/events.py", line 103, in on_get_instance
    return value[0]["link"]["entity"]
IndexError: list index out of range

**Comment by AndrejGorodnij** [comment]
Добавил PR для фикса
