### ISSUE TITLE
Помогите с кастомными полями

### ISSUE THREAD

**Issue by IriskaID** [Krukov/amocrm_api#91]
Пытался решить проблему с помощью https://github.com/Krukov/amocrm_api/issues/90, но безуспешно. 

Кусок кода: 
`class Lead(_Lead):
    rasshifrovka = custom_field.UrlCustomField("Расшифровка", field_id=1400397)`

( на самом деле кастомных полей больше)

`        existing_lead = Lead.objects.get(query=checkbox[0])
        # Обновляем данные существующей сделки
        existing_lead.rasshifrovka = checkbox[12]
        existing_lead.price = convert_sum(checkbox[2])
        existing_lead.save()` 
 
Если закомментировать строчки с кастомными полями и оставить только стандартные, то все заработает. Если есть кастомные поля(любые), то выпадет ошибка. 
Удивительно то, что все работает на моем аккаунте, но не работает на аккаунте заказчика. Создание новых сделок тоже работает отлично.

Ошибка
`Traceback (most recent call last):
  File "crmAPI.py", line 193, in <module>
    upd_lead(check_checkbox())
  File "crmAPI.py", line 189, in upd_lead
    create_a_deal(checkbox)
  File "crmAPI.py", line 161, in create_a_deal
    existing_lead.update()
  File "/root/crm_integration/venv/lib/python3.6/site-packages/amocrm/v2/model.py", line 63, in update
    self._manager.update(self.id, self._get_updated_data())
  File "/root/crm_integration/venv/lib/python3.6/site-packages/amocrm/v2/manager.py", line 19, in update
    return self._interaction.update(object_id=object_id, data=data or kwargs)
  File "/root/crm_integration/venv/lib/python3.6/site-packages/amocrm/v2/interaction.py", line 132, in update
    raise exceptions.ValidationError(response)
amocrm.v2.exceptions.ValidationError: {'validation-errors': [{'request_id': '0', 'errors': [{'code': 'FieldNotExpected', 'path': 'custom_fields_values.0.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.1.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.2.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.3.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.4.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.5.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.6.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.7.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.8.is_computed', 'detail': 'This field was not expected.'}, {'code': 'FieldNotExpected', 'path': 'custom_fields_values.9.is_computed', 'detail': 'This field was not expected.'}]}], 'title': 'Bad Request', 'type': 'https://httpstatus.es/400', 'status': 400, 'detail': 'Request validation failed'}`

**Comment by alex-msk** [comment]
Быть может проблема в том, что field_id у заказчика и у Вас отличаются?

**Comment by IriskaID** [comment]
> Быть может проблема в том, что field_id у заказчика и у Вас отличаются?

нет, ошибка не в этом т.к я получил все новые поля с помощью 

`export AMOCRM_CLIENT_ID=xxx
export AMOCRM_SECRET=xxx
export AMOCRM_SUBDOMAIN=xxx
export AMOCRM_REDIRECT_URL=xxx
export AMOCRM_CODE=xxx # optional
pyamogen > models.py`

Как было выше сказано, создание новых сделок на аккаунте заказчика работает корректно

**Comment by IriskaID** [comment]
> Быть может проблема в том, что field_id у заказчика и у Вас отличаются?

ваш тикет я тоже изучил (https://github.com/Krukov/amocrm_api/issues/68)
Добавил в код схожий костыль
`        company = Company(name=checkbox[6], adres=checkbox[7])
        for c in company._data["custom_fields_values"]:
            if "field_code" in c:
                del c["field_code"]
            if "values" in c:
                for v in c["values"]:
                    if "enum_code" in v:
                        del v["enum_code"]
        company.save()`
 Но проблема продолжает появляться.
 
 Вот полный блок кода, отвечающий за создание/обновление сделки
 `def create_a_deal(checkbox):
    if list(Lead.objects.filter(query=checkbox[0])):
        existing_lead = Lead.objects.get(query=checkbox[0])
        # Обновляем данные существующей сделки
        existing_lead.rasshifrovka = checkbox[12]
        existing_lead.price = convert_sum(checkbox[2])
        # # обновляем
        existing_lead.podborka = checkbox[13]
        existing_lead.tekh_zadanie = checkbox[14]
        existing_lead.razmeshchen = checkbox[3]
        existing_lead.okonchanie_podachi_zaiavok = checkbox[4]
        existing_lead.podvedenie_rezultatov = checkbox[5]
        existing_lead.price = convert_sum(checkbox[2])
        existing_lead.papka_sdelki = checkbox[11]
        existing_lead.google_folder_link_leads_field = checkbox[11]
        existing_lead.status_auktsiona = get_auktsion_status(checkbox[9])
        existing_lead.save()
    else:
        # создаем новую сделку и заполняем данными из таблички
        new_deadl = Lead.objects.create()
        new_deadl.name = checkbox[0]
        new_deadl.pipeline = config.pipeline_id
        new_deadl.status = config.status_id
        new_deadl.nomer_auktsiona = checkbox[0]
        new_deadl.ssylka_na_auktsion = checkbox[1]
        new_deadl.rasshifrovka = checkbox[12]
        new_deadl.podborka = checkbox[13]
        new_deadl.tekh_zadanie = checkbox[14]
        new_deadl.razmeshchen = checkbox[3]
        new_deadl.okonchanie_podachi_zaiavok = checkbox[4]
        new_deadl.podvedenie_rezultatov = checkbox[5]
        new_deadl.price = convert_sum(checkbox[2])
        new_deadl.papka_sdelki = checkbox[11]
        new_deadl.google_folder_link_leads_field = checkbox[11]
        new_deadl.status_auktsiona = get_auktsion_status(checkbox[9])
        # создание компании внутри сделки
        company = Company(name=checkbox[6], adres=checkbox[7])
        for c in company._data["custom_fields_values"]:
            if "field_code" in c:
                del c["field_code"]
            if "values" in c:
                for v in c["values"]:
                    if "enum_code" in v:
                        del v["enum_code"]
        company.save()
        # Добавляем компанию к списку компаний, связанных со сделкой
        new_deadl.contacts.append(company)
        new_deadl.save()`

**Comment by IriskaID** [comment]
UPD: отписал в техническую поддержку. Код верный, иначе бы он на другом аккаунте не работал. Даже с новым тестовым полем выбивает эту же ошибку

**Comment by IriskaID** [comment]
https://pastebin.pl/view/dd809566
отловил запросы, которые отправляет библиотека. Проблема остается

**Comment by IriskaID** [comment]
Удалось исправить. Библиотека передавала лишний ключ is_computed. 
Проблема решилась модификацией функции update в файле interaction.py
`    def update(self, object_id, data):
        path = "{}/{}".format(self._get_path(), object_id)
        for item in data['custom_fields_values']:
            item.pop('is_computed', None)
        response, status = self.request("patch", path, data=data)
        if status == 400:
            raise exceptions.ValidationError(response)
        return response`

**Comment by Krukov** [comment]
А почему это поле на вашем акаунте не передавалось ? 

Видимо в некоторых случаях апи амосрим на получении сушьности добавляет лишнее поля а выдачу апи которы не описаны в документации 

Нужно поправить в библиотеке - убрать при формировании обновлении кастомного поле лишние поля ( брать только values, field_name, field_code
